id: P9BFA0F25
initial_creation_type: ocr
source_metadata:
  volumes:
    35f4824a598141bdac5a8f92a6343168:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་ལྷ་མོ་སྒྲོལ་མ་ལ་བསྟོད་པ།
      total_pages: 1648
      volume_number: 40
